#!/usr/bin/env bash

# IP address of linked container
# Assumes alias of "FPM"
if [ -z "$FPM_PORT_9000_TCP_ADDR" ]; then
    echo "Linked container of alias 'FPM' not found. Must expose port 9000."
    exit 1
fi


# Replace with linked container env var
sed -i "s/FPM_PORT_9000_TCP_ADDR/$FPM_PORT_9000_TCP_ADDR/" /etc/nginx/sites-enabled/default

#ls -ald /var/lib/nginx
#mkdir /var/lib/nginx/body
#chmod 2755 /var/www


# Start nginx
nginx